Update dependencies (2025-08-04) (#521)
* Add link to VSCode extension.

This is to make it easier to look up what version is currently shipping
with the extension.

* Update deps.

* Update deps and build with Go 1.24.

* Update deps.

* Update UI deps.

* Downgrade pytest-subtests to 0.14.1.

0.14.2 causes test failures when using pytest-xdist:
execnet.gateway_base.DumpError: can't serialize <class 'datetime.datetime'>