Temporarily use Python 3.13 in boxed-musl.
This works around a runtime error with Python 3.12 on Musl:
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'

Other imports are affected; Pydantic is just the most common we've
seen.

This fix has not yet been backported to a Python 3.12 release, so we
will install 3.13 for now.