Downgrade pytest-subtests to 0.14.1.
0.14.2 causes test failures when using pytest-xdist:
execnet.gateway_base.DumpError: can't serialize <class 'datetime.datetime'>